// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "PortalGun.generated.h"

class ACustomPortal;
class APortalGunShooterCharacter;

UCLASS()
class PORTALGUNIMPLEMENT_API APortalGun : public AActor
{
	GENERATED_BODY()
	
	/** First person perspective mesh */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components", meta = (AllowPrivateAccess = "true"))
	USkeletalMeshComponent* FirstPersonMesh;

	/** Third person perspective mesh */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Components", meta = (AllowPrivateAccess = "true"))
	USkeletalMeshComponent* ThirdPersonMesh;
	
protected:
	//해당 액터(포탈건)를 들고있을 플레이어
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Weapon")
	TObjectPtr<APortalGunShooterCharacter> PortalHoldingPlayer;
	
	// 스폰할 포탈 클래스 (from PortalGunComponent)
	UPROPERTY(EditAnywhere, Category = "Portal")
	TSubclassOf<class ACustomPortal> PortalClass;
	
	// 현재 월드에 생성된 포탈들의 주소를 기억하고 새로 쓸 대 기존 것을 지우는 로직 담당을 위해
	//생성된 파란색 포탈의 주소를 기억합니다. (from PortalGunComponent)
	UPROPERTY(Transient)
	TObjectPtr<ACustomPortal> BluePortal;
	
	//생성된 주황색 포탈의 주소를 기억합니다. (from PortalGunComponent)
	UPROPERTY(Transient)
	TObjectPtr<ACustomPortal> OrangePortal; 
	
	/** AnimInstance class to set for the first person character mesh when this weapon is active (from ShooterWeapon(ArenaShooter)) */
	UPROPERTY(EditAnywhere, Category="Animation")
	TSubclassOf<UAnimInstance> FirstPersonAnimInstanceClass;
	
	/** AnimInstance class to set for the third person character mesh when this weapon is active (from ShooterWeapon(ArenaShooter))*/
	UPROPERTY(EditAnywhere, Category="Animation")
	TSubclassOf<UAnimInstance> ThirdPersonAnimInstanceClass;
	
	/** Name of the first person muzzle socket where PortalBeamEffect will spawn (from ShooterWeapon(ArenaShooter))*/
	UPROPERTY(EditAnywhere, Category="Aim")
	FName MuzzleSocketName = FName("Muzzle");;
	
	/** Distance ahead of the muzzle that bullets will spawn at (from ShooterWeapon(ArenaShooter))*/
	UPROPERTY(EditAnywhere, Category="Aim", meta = (ClampMin = 0, ClampMax = 1000, Units = "cm"))
	float MuzzleOffset = 10.0f;
	
	//일단 추가
	/** Loudness of the shot for AI perception system interactions */
	UPROPERTY(EditAnywhere, Category="Perception", meta = (ClampMin = 0, ClampMax = 100))
	float ShotLoudness = 1.0f;

	/** Max range of shot AI perception noise */
	UPROPERTY(EditAnywhere, Category="Perception", meta = (ClampMin = 0, ClampMax = 100000, Units = "cm"))
	float ShotNoiseRange = 3000.0f;

	/** Tag to apply to noise generated by shooting this weapon */
	UPROPERTY(EditAnywhere, Category="Perception")
	FName ShotNoiseTag = FName("Shot");
public:	
	// Sets default values for this actor's properties
	APortalGun();
	
	/** 캐릭터의 발사 신호를 수신 (0: 블루, 1: 오렌지) from PortalGunComponent*/
	UFUNCTION()
	void HandlePortalShot(int32 PortalColorIndex);

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;
	
	/** 실제 포탈 발사 로직 from PortalGunComponent*/
	void ExecutePortalTrace(int32 ColorIndex);

public:	
	/** 캡슐화: 메쉬 접근용 */
	USkeletalMeshComponent* GetFirstPersonMesh() const { return FirstPersonMesh; }
	
	USkeletalMeshComponent* GetThirdPersonMesh() const { return ThirdPersonMesh; }
	
	/** Returns the first person anim instance class */
	const TSubclassOf<UAnimInstance>& GetFirstPersonAnimInstanceClass() const;

	/** Returns the third person anim instance class */
	const TSubclassOf<UAnimInstance>& GetThirdPersonAnimInstanceClass() const;
	// Called every frame
	//virtual void Tick(float DeltaTime) override;

};
